# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}
ENV container=docker
ENV LC_ALL C

{% if item.environment.http_proxy is defined %}
RUN echo proxy={{ item.environment.http_proxy }} >> /etc/yum.conf
{% endif %}

RUN sed -i 's/mirrorlist=/#mirrorlist=/' /etc/yum.repos.d/*.repo \
	&& sed -i 's/#baseurl=/baseurl=/' /etc/yum.repos.d/*.repo \
	&& yum -y install iptables which

# Start

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/lib/systemd/systemd"]
