- name: Converge
  hosts: all
  tasks:
  - name: Include ../../..
    include_role:
      name: ../../..
  vars:
    consul_http_proxy: "{{ lookup('env','http_proxy') }}"
    consul_https_proxy: "{{ lookup('env','https_proxy') }}"
    consul_http_no_proxy: "{{ lookup('env','no_proxy') }}"
    consul_ui_content_path: /consul/
    consul_server_mode: true
    consul_consul_bootstrap_expect: 1
    consul_client_addr: # client API
    - 127.0.0.1     # localhost
