heat_template_version: 2017-09-01

description: Grafana / InfluxDB deployment

#######################################################
# Parameters
parameters:
    image_id:
        type: string
        description: Operating system image to use
        default: ubuntu18.04_server
        constraints:
            - custom_constraint: glance.image

    front_net_id:
        type: string
        description: Network ID to use for the appliance
        constraints:
            - custom_constraint: neutron.network

    back_net_id:
        type: string
        description: Network ID to use for the appliance
        constraints:
            - custom_constraint: neutron.network

    os_username:
        type: string
        description: Cloud username for some internal batches

    os_password:
        type: string
        description: Cloud password for some internal batches
        hidden: true

    os_auth_url:
        type: string
        description: Cloud auth URL

    os_region_name:
        type: string
        description: Cloud region name

    git_repo_url:
        type: string
        description: cloud-appliance-observability repo
        default: https://github.com/139bercy/cloud-appliance-observability

    git_repo_checkout:
        type: string
        description: branch/tag/commit to use
        default: master

    default_secgroup_id:
        type: string
        description: Default security group to use
        constraints:
            - custom_constraint: neutron.security_group

    internet_http_proxy_url:
        type: string
        description: HTTP proxy

    internet_http_no_proxy:
        type: string
        description: Proxy skiplist

    ntp_server:
        type: string
        description: Remote NTP to use for sync

    static_hosts:
        type: string
        description: JSON array of host:ip tuples
        default:

    flavor:
        type: string
        description: Cloud flavor to use
        constraints:
            - custom_constraint: nova.flavor

    metrics_size_gb:
        type: number
        description: InfluxDB and Grafana data size (Gb)
        default: 100
        constraints:
            - range: { min: 1 }
              description: Size must be set to at least 1Gb.

    grafana_admin_name:
        type: string
        description: Grafana admin username

    grafana_admin_password:
        type: string
        description: Grafana admin password
        hidden: true

    influxdb_admin_name:
        type: string
        description: InfluxDB admin username

    influxdb_admin_password:
        type: string
        description: InfluxDB admin password
        hidden: true
        constraints:
            - length: { min: 9 }
              description: Password length must be between at least 10.

    influxdb_organisation:
        type: string
        description: InfluxDB Org name
        constraints:
            - length: { min: 4 }
              description: Organisation name length must be between at least 5.
            - allowed_pattern: "[a-zA-Z0-9]+"
              description: Organisation name must be alpha-numeric.

    influxdb_retention_hours:
        type: number
        description: InfluxDB default retention (hours)
        constraints:
            - range: { min: 1 }
              description: Retention must be positive

    metrics_endpoint_url:
       type: string
       description: Public hostname used to connect against the tools

    metrics_container:
       type: string
       description: Swift container to use for backups

    consul_usage:
       type: boolean
       description: Do we use consul?
       default: false

    consul_dns_domain:
       type: string
       description: DNS domain used by Consul agent
       default: cloud

    consul_datacenter:
       type: string
       description: Datacenter name used by Consul agent
       default: dc1

    consul_encrypt:
       type: string
       description: Consul shared secret for cluster communication
       hidden: true
       default: VTZ4XZCX3XgMUxPMQ4ZhY4U+ewBDx5VMPrGbx94l6Hc=
       constraints:
            - length: { min: 44, max: 44 }

    consul_dns_server:
       type: string
       description: IP address to use for non-consul-managed domains
       default: 

resources:

#######################################################
# Startup script

    node_boot_script:
        type: OS::Heat::SoftwareConfig
        properties:
            config:
                str_replace:
                    params:
                        $internet_http_proxy_url: { get_param : internet_http_proxy_url }
                        $internet_http_no_proxy: { get_param : internet_http_no_proxy }
                        $static_hosts: { get_param: static_hosts }

                        $git_repo_checkout: { get_param: git_repo_checkout }
                        $git_repo_url: { get_param: git_repo_url }

                        $os_password: { get_param: os_password }
                        $os_username: { get_param: os_username }
                        $os_auth_url: { get_param: os_auth_url }

                        $grafana_admin_name: { get_param: grafana_admin_name }
                        $grafana_admin_password: { get_param: grafana_admin_password }
                        $influxdb_admin_name: { get_param: influxdb_admin_name }
                        $influxdb_admin_password: { get_param: influxdb_admin_password }
                        $influxdb_organisation: { get_param: influxdb_organisation }
                        $influxdb_retention_hours: { get_param: influxdb_retention_hours }
                        $metrics_endpoint_url: { get_param: metrics_endpoint_url }
                        #$metrics_container: { get_resource: metrics_swift }
                        $metrics_container: { get_param: metrics_container }

                        $cinder_containers_volume: { get_resource: appliance_containers_volume }
                        $cinder_metrics_volume: { get_resource: appliance_metrics_volume }

                        $consul_usage: { get_param: consul_usage }
                        $consul_dns_domain: { get_param: consul_dns_domain }
                        $consul_datacenter: { get_param: consul_datacenter }
                        $consul_encrypt: { get_param: consul_encrypt }
                        $consul_dns_server: { get_param: consul_dns_server }

                        $appliance_back_port : { get_resource: appliance_back_port }
                        $ntp_server: { get_param: ntp_server }
                    template: |
                        #!/bin/bash
                        set -x

                        # Proxy
                        export HTTPS_PROXY=$internet_http_proxy_url
                        export HTTP_PROXY=$internet_http_proxy_url
                        export NO_PROXY=$internet_http_no_proxy,127.0.0.1,localhost,0.0.0.0
                        export https_proxy=$internet_http_proxy_url
                        export http_proxy=$internet_http_proxy_url
                        export no_proxy=$internet_http_no_proxy,127.0.0.1,localhost,0.0.0.0

                        # Install required packages to start git-ops-based auto-configuratiom
                        if which yum > /dev/null 2>&1 ; then
                            sed -i 's/gpgcheck=1/gpgcheck=1\nproxy=_none_/g' /etc/yum.repos.d/centos.repo
                            sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/epel.repo

                            if [ ! -z "$HTTP_PROXY" ] ; then
                                grep -q proxy= /etc/yum.conf || echo "proxy=$HTTP_PROXY" >> /etc/yum.conf
                            fi

                            yum install --assumeyes ansible git jq unzip > /dev/null
                        else
                            apt update > /dev/null
                            apt -y install \
                                ansible git jq \
                                python3-swiftclient python3-openstackclient \
                                unzip \
                                libgpgme11 > /dev/null
                        fi

                        # DNS: Populate /etc/hosts
                        if [ ! -z "$static_hosts" ] ; then
                            echo $static_hosts > /tmp/static_hosts
                            cat /tmp/static_hosts \
                                | perl -pe 's/\[|\]|{|}//g' \
                                |  tr ',' '\n' \
                                | awk -F: '{print $2,$1}' \
                                | awk '{print $1,$2}' \
                                >> /etc/hosts
                        fi

                        # Configure ansible to work without an entire environment set
                        sed -i 's/~/\/root/' /etc/ansible/ansible.cfg
                        sed -i 's/^#remote_tmp/remote_tmp/' /etc/ansible/ansible.cfg
                        sed -i 's/^#local_tmp/remote_tmp/' /etc/ansible/ansible.cfg

                        # Create local facts folder
                        mkdir -p /etc/ansible/facts.d

                        # Clone the bootstrap git repository
                        export REPO_PATH=/root/appliance
                        export ETC_PATH=$REPO_PATH/etc
                        export PLAYBOOK=$REPO_PATH/metrics/metrics.appliance.playbook.yml

                        ## Set the Openstack credentials
                        export OS_AUTH_URL="$os_auth_url"
                        export OS_PROJECT_ID=$(awk -F'"' '/project_id/ {print $4}' /run/cloud-init/instance-data.json)
                        export OS_USER_DOMAIN_NAME="Default"
                        export OS_USERNAME="$os_username"
                        export OS_PASSWORD="$os_password"
                        export OS_REGION_NAME="RegionOne"
                        export OS_INTERFACE=public
                        export OS_IDENTITY_API_VERSION=3
                        
                        # Swift container
                        export METRICS_CONTAINER=$metrics_container

                        # Set the volumes' IDs
                        export CONTAINERS_VOLUME=$cinder_containers_volume
                        export METRICS_VOLUME=$cinder_metrics_volume
                        
                        # Set the Grafana credentials
                        export GRAFANA_ADMIN_NAME="$grafana_admin_name"
                        export GRAFANA_ADMIN_PASSWORD="$grafana_admin_password"
                        # Set the InfluxDB credentials
                        export INFLUXDB_ADMIN_NAME="$influxdb_admin_name"
                        export INFLUXDB_ADMIN_PASSWORD="$influxdb_admin_password"
                        export INFLUXDB_ORG="$influxdb_organisation"
                        export INFLUXDB_RETENTION_HOURS="$influxdb_retention_hours"
                        # Set metrics endpoint
                        export METRICS_ENDPOINT_URL="$metrics_endpoint_url"
                        
                        # Set Consul variables
                        export CONSUL_USAGE="$consul_usage"
                        export CONSUL_DNS_DOMAIN="$consul_dns_domain"
                        export CONSUL_DATACENTER="$consul_datacenter"
                        export CONSUL_ENCRYPT="$consul_encrypt"
                        export CONSUL_DNS_SERVER="$consul_dns_server"

                        # Test proxy and Openstack endpoint
                        curl -m1 -vks $HTTP_PROXY > /dev/null
                        openstack server list
                        export BACK_IP=$(openstack port show $appliance_back_port -c fixed_ips | perl -ne '/ip_address=.([\d|\.]+)., / && print $1')

                        # Set NTP variables
                        export NTP_SERVER=$ntp_server

                        # Autoconf the appliance
                        curl -m1 -vks $git_repo_url > /dev/null
                        git clone -b $git_repo_checkout $git_repo_url $REPO_PATH || exit 1

                        . $REPO_PATH/metrics/metrics.appliance.autoconf.sh

                        # Stop secure shell
                        systemctl stop ssh
                        systemctl disable ssh

#######################################################
# Security group

    metrics_appliance_secgroup:
        type: OS::Neutron::SecurityGroup
        properties:
            description: Security group with webservices ports
            name: metrics-appliance
            rules: [
                {
                    protocol: tcp,
                    port_range_min: 80,
                    port_range_max: 80,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
                {
                    protocol: tcp,
                    port_range_min: 443,
                    port_range_max: 443,
                    remote_ip_prefix: 0.0.0.0/0,
                    direction: ingress
                },
            ]

#######################################################
# Appliance

    appliance_front_port:
        type: OS::Neutron::Port
        properties:
            network_id: { get_param: front_net_id }
            security_groups: [
                { get_param: default_secgroup_id }
            ]

    appliance_back_port:
        type: OS::Neutron::Port
        properties:
            network_id: { get_param: back_net_id }
            security_groups: [
                { get_param: default_secgroup_id },
                { get_resource: metrics_appliance_secgroup }
            ]

    appliance:
        type: OS::Nova::Server
        properties:
            name: metrics
            image: { get_param: image_id }
            flavor: { get_param: flavor }
            networks:
                - port: { get_resource: appliance_front_port }
                - port: { get_resource: appliance_back_port }
            metadata: {
                group: observability,
                image: { get_param: image_id }
            }
            user_data_format: SOFTWARE_CONFIG
            user_data: { get_resource: node_boot_script }

    appliance_metrics_volume:
        type: OS::Cinder::Volume
        properties:
            name: metrics-metrics-appliance
            size: { get_param: metrics_size_gb }

    appliance_metrics_attachment:
        type: OS::Cinder::VolumeAttachment
        properties:
            volume_id: { get_resource: appliance_metrics_volume }
            instance_uuid: { get_resource: appliance }

    appliance_containers_volume:
        type: OS::Cinder::Volume
        properties:
            name: containers-metrics-appliance
            size: 3

    appliance_containers_attachment:
        type: OS::Cinder::VolumeAttachment
        properties:
            volume_id: { get_resource: appliance_containers_volume }
            instance_uuid: { get_resource: appliance }

#    metrics_swift:
#        type: OS::Swift::Container
#        properties:
#            name: metrics

#######################################################
# Outputs

#outputs:
